config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root to: 'pages#home'

  resources :users, only: [:show]

  resources :rankings, only: [:index] do
    collection do
      get 'rules'
      get 'synopsis'
    end
  end

  resources :games, only: [:show, :create] do
    resources :participations, only: [:index]
  end

  resources :participations, only: [:create]
  resource :participations, only: [:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :participations, dependent: :destroy
  enum status: [:waiting, :start, :end]

  MAX_PLAYERS_COUNT = 3

  def winner
    participations.find do |participation|
      participation.score == 500
    end
  end

  def elapsed_time
    return 0 if ended_at == nil || started_at == nil
    (ended_at - started_at).round(1)
  end

  def self.winners_with_times
    games=Game.played_games.map do |game|
      next if game.winner.nil?
      { winner: game.winner, time: game.elapsed_time }
    end
    games.compact.sort_by { |hash| hash[:time] }
  end

  def self.played_games
    all.select { |game| game.status == "end" }
  end

  def start_if_needed
    return false unless participations.count == MAX_PLAYERS_COUNT
    if self.start!
      GameChannel.broadcast_to(
        self,{
          action: "game_starting",
          content: ActionController::Base.new.render_to_string(partial: "games/gameplay", locals: { game: self })
        }
      )
    end
  end
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :game

  def elapsed_time
    (game.ended_at - game.started_at).round(2)
  end
end

app/models/ranking.rb
class Ranking < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  has_many :participations
  validates :email, :password, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/models/waiting_room.rb
class WaitingRoom < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:pseudo, :email, :password) }
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def show
    @game = Game.find(params[:id])
    @participations = @game.participations
  end

  def create
    @game = Game.find_by(status: :waiting)
    @game ||= Game.create(status: :waiting, started_at: DateTime.now)
    redirect_to game_path(@game)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/participation.rb
class WaitingRoomsController < ApplicationController
  def index
    @waiting_rooms = WaitingRoom.all
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  def index
    @participations = Participation.last(2)
  end

  def create
    @participation = Participation.new
    @participation.user = current_user
    @game = Game.last
    @participation.game = @game
    return if @game.participations.where(user: current_user).any?

    if @participation.save
      @participations = @game.participations
      GameChannel.broadcast_to(
        @game,{
          action: "new_participation",
          content: render_to_string(partial: "participations", locals: { participations: @participations })}
      )
      @game.start_if_needed
    else
      redirect_to root_path
    end
  end

  def update
    @participation = Participation.where(user_id: params['user_id'], game_id: params['game_id']).first
    # TODO METTRE UNE VALEUR PAR DEFAUT ET INCREMENTER
    @participation.update(score: @participation.score += 100, kill_count: @participation.kill_count += 1)

    if @participation.score == 500
      @game = Game.find(params['game_id'])
      @game.update(ended_at: DateTime.now, status: :end)
      @participations = @game.participations.order(score: :desc)
      GameChannel.broadcast_to(
        @game,{
          action: "game_end",
          content: render_to_string(partial: "games/results", locals: { participations: @participations })
        }
      )
    end
  end
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  def index
    @winners = Game.winners_with_times.first(8)

    # @datas = []
    # User.all.each do |user|
    #   data = { user: user }
    #   times = []
    #   user.participations.each do |participation|
    #     next if participation.game.started_at == nil
    #     next if participation.game.ended_at == nil
    #     next if participation.elapsed_time == nil
    #     times << participation.elapsed_time unless (participation.elapsed_time == nil) || (participation == nil)
    #   end
    #   data[:time] = times.min unless times.min == nil
    #   @datas << data
    # end
  end

  def rules
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_gameplay.html.erb
<canvas id = 'canvas' class= 'canvas' data-controller='game' data-action='game-end@window->game#stop'>
</canvas>

app/views/games/_results.html.erb
<h1 class="title-congrats">Congratulation !</h1>
<div class="pyro">
  <div class="before"></div>
  <div class="after"></div>
</div>
<div class="all-data">
  <div class="container-data2">
    <p class="stats" >Game Time: <%= participations.last.elapsed_time %>s</p>
  </div>
    <div class="container-data1">
      <p class="stats">Rank</p>
      <p class="stats">Name</p>
      <p class="stats">Kill</p>
      <p class="stats">Score</p>
    </div>
    <ul class="p-0">
    <% participations.each_with_index do |participation, index| %>
      <li style= "list-style: none;">
        <div class="container-data">
          <p class="stats"><%= index + 1 %></p>
          <p class="stats"><%= participation.user.pseudo %></p>
          <p class="stats"><%= participation.kill_count %></p>
          <p class="stats"> <%= participation.score %></p>
        </div>
      </li>
    <% end %>
  </ul>
</div>
<div class="btn-display">
  <%= link_to "New Game", games_path, method: :post, class: "btn-newgame"%>
  <%= link_to "Quit", root_path, class:"btn-quit"%>
</div>

app/views/games/new.html.erb
<h1>hello world</h1>

app/views/games/show.html.erb
<div class="container-game" data-controller='game-subscriptions audio' data-game-subscriptions-game-id-value="<%= @game.id %>">
  <h1>Lobby n° <%= @game.id %></h1>
  <div id='canvas-container' data-game-subscriptions-target="gameContainer" data-user-id=<%= current_user.id %>>
    <%= render 'participations/participations', participations: @participations %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MotionBattle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>

    <% unless params[:controller] == 'users' %>
      <%= render "shared/avatar" %>
    <% end %>

    <%= render 'shared/flashes' %>

    <%= yield %>
    <div class="firefly"></div>
    <div class="firefly"></div>
    <div class="firefly"></div>
    <div class="firefly"></div>
    <div class="firefly"></div>
    <div class="firefly"></div>
    <div class="firefly"></div>
    <div class="firefly"></div>
    <div class="firefly"></div>
    <div class="firefly"></div>
    <div class="firefly"></div>
    <div class="firefly"></div>
    <div class="firefly"></div>
  </body>
</html>

app/views/pages/home.html.erb
<div class ="title">
  <h1>Motion Battle </h1>
</div>
<div data-controller="audio" class = "btns-home">
    <div class="new-game" >
      <%= button_to "New Game", games_path, method: :post, class: "laduchbtn" %>
    </div>
    <div class="rules-option">
      <%= link_to "Rules", rules_rankings_path, class: "laduchbtn"%>
      <%= link_to "Options", root_path, class: "laduchbtn"%>
    </div>
    <div class = "quit">
      <%= link_to "Synopsis", synopsis_rankings_path, class: "laduchbtn"%>
    </div>
  </div>
</div>

app/views/participations/_participations.html.erb
<div data-game-subscriptions-target="subscriptions">
    <p>Click on <em>"waiting line"</em> and wait for your friends to start the game</p>
    <%= button_to "waiting line", participations_path, method: :post, remote: true, class:"btn-queue", data: {action: 'click->game-subscriptions#start'} %>
  <% participations.each do |participation| %>
    <ul class='waiting-participations'>
      <li>
        <%= participation.user.pseudo %>
      </li>
    </ul>
  <% end %>
</div>

app/views/participations/index.html.erb
<h1 class="title-congrats">VICTORY / DEFEAT</h1>
<div class="all-data">
  <div class="container-data">
    <p class="stats">Rank</p>
    <p class="stats">Name</p>
    <p class="stats">Survival Time</p>
    <p class="stats">Kill(s)</p>
  </div>
  <div class="pyro">
  <div class="before"></div>
  <div class="after"></div>
</div>
  <div class="container-data">
    <% @participations.each_with_index do |participation, index| %>
      <p class="stats"><%= index + 1 %></p>
      <p class="stats"><%= participation.user.pseudo %></p>
      <p class="stats">TODO GAME DURATION</p>
      <p class="stats"><%= participation.kill_count %></p>
    <% end %>
  </div>
</div>
<div class="btn-display">
  <%= link_to "New Game",  games_path, method: :post, class: "btn-newgame"%>
  <%= link_to "Quit", root_path, class:"btn-quit"%>
</div>

app/views/rankings/index.html.erb
<div class="ranking-csgo">
  <h1>World Fastest Player</h1>

  <div class="ranking-stats">

      <% @winners.each do |data| %>
        <div class="coucou">
          <p><%= data[:winner].user.pseudo %></p>
          <p><em><%= data[:time] %>s</em></p>
        </div>
      <% end %>

  </div>
    <%= link_to "Home", root_path, class: "laduchbtn", id:"laduch3"%>
</div>

app/views/rankings/rules.html.erb
<div class="rules-container">
  <h1>Motion battle</h1>
  <h2>Rules of the game</h2>
  <ul>
    <li>The first to kill all the dragons and manages to beat the big boss and wins the game 🦖</li>
    <li>Game recommended for ages 1 to 111</li>
    <li>Cheating is strictly prohibited undenalty of non-reversible banishment from our moderation service 🚫</li>
    <li>Thank you for being polite and courteous to everyone for a better gaming experience</li>
    <li>Shop coming soon 🤫 </li>
  </ul>
</div>
<div class="rules-back">
  <%= link_to "Back", root_path, class: "laduchbtn"%>
</div>

app/views/rankings/synopsis.html.erb
<div class="container-texte-deroulant">
  <div class="text-deroulant">
  <h1>Synopsis</h1>
  </div>
  <div class="text-explicatif">
    <marquee behavior="scroll" direction="up" width="80%" height="485" bgcolor="transparent" scrollamount="1">
      <h2>In the peaceful valley of Cragbury everything went perfectly. <br> Sam loved playing with his loving parents.
      <br>
      Unfortunately one day, the awful Saruman decided to unleash his dragons to destroy its inhabitants.
      <br> 6-year-old Sam saw her parents being devoured.
      <br>
      He promised himself to avenge them.
      <br>
      Now 18, Sam no longer wants to hide, he feels strong enough to free the world from its dragons and avenge his parents ! </h2>
    </marquee>
    <div class ="laduchbtn2">
      <%= link_to "Home", root_path, class: "text-reset" %>
    </div>
</div>

app/views/shared/_avatar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon :">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <%= link_to "World Best Players", rankings_path, class: "volvic-fraise"%>
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "avatarche.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end hamburger" aria-labelledby="navbarDropdown" >
              <%= link_to "Profile", user_path(current_user), class: "dropdown-item dropdown-text" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item dropdown-text" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag " ", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="title-profil" >
  <h1>Profil</h1>
</div>
<div class="">
  <%= image_tag "avatarche.jpg", class: "avatar-large", alt: "avatar-large" %>
</div>
<div class="pseudo-user"><%= current_user.pseudo %></div>
<div class= "w-100">
<div class="container-data-users-show mx-auto">
  <p class="stats">Games Played: <em><%= current_user.participations.count %></em></p>
</div>
<div class="container-data-users-show mx-auto">
  <p class="stats">Win: <em><%= current_user.participations.where(score: 500).count %></em> </p>
</div>
<div class="container-data-users-show mx-auto">
  <p class="stats">Kill: <em><%= current_user.participations.sum(:kill_count) %></em> </p>
</div>
<div class="container-data-users-show mx-auto">
  <p class="stats">Total Score: <em><%= current_user.participations.sum(:score) %></em></p>
</div>
</div>
<div class="quit-home">
<%= link_to "World Best Players", rankings_path, class: "laduchbtn", id: "petitfdp"%>
</div>
<div class="quit-home">
<%= link_to "Home", root_path, class: "laduchbtn"%>
</div>


<%# <div class="">
  <%# @participations.each_with_index do |participation, index| %>
  <%# <p class="stats"><%= participation.user.pseudo %> <%# </p>
  <%# <p class= "stats"><%= participation.win_count %> <%# </p>
  <%# <p class="stats"><%= participation.kill_count %> <%#/p>
  <%# <p class="Score Total"><%= participation.score.all%> <%#</p>
    <%# end %>
<%# </div> %>